services:

  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: ems_api
    working_dir: /var/www
    volumes:
      - ./Backend:/var/www
    depends_on:
      - db
    ports:
      - "8080:8000"
    environment:
      APP_ENV: dev
      DB_HOST: db
      DB_NAME: ems
      DB_USER: ems
      DB_PASSWORD: secret
    command: >
      sh -c "
      composer install &&
      php -S 0.0.0.0:8000 -t public
      "



  db:
    image: mysql:8.0
    container_name: ems_db
    restart: always
    environment:
      MYSQL_DATABASE: ems
      MYSQL_USER: ems
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql



  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: ems_frontend
    working_dir: /app
    volumes:
      - ./Frontend:/app
    ports:
      - "3000:5173"
    depends_on:
      - api
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"



volumes:
  db_data:
